`ifndef AHB_IF_INCLUDED_
`define AHB_IF_INCLUDED_

interface ahb_if(input clk, input resetn);
    // signal generate from mananger
    logic [ADDR_WIDTH-1 : 0]    haddr;
    logic [HBURST_WIDTH-1:0]    hburst;
    logic                       hmastlock;
    logic [HPROT_WIDTH-1:0]     hprot;
    logic [2:0]                 hsize;
    logic                       hnonsec;
    logic                       hexcl;
    logic [HMASTER_WIDTH-1:0]   hmaster;
    logic [1:0]                 htrans;
    logic [DATA_WIDTH-1:0]      hwdata;
    logic [HWSTRB-1:0]          hwstrb;
    logic                       hwrite;
    // singal generate by subordinate
    logic [DATA_WIDTH-1:0]      hrdata;
    logic                       hreadyout;
    logic                       hresp;
    logic                       hexokey;
    //signal generated by decoder
    //logic                       hsel;
    //signal generated by multiplexor, if 
    logic                       hready;
    
import uvm_pkg::*;
`include "uvm_macros.svh";

initial begin
    `uvm_info("ASSERTIONS","///////--------------------ASSERTIONS--------------------///////",UVM_LOW);
end
property singal_alway_valid;
    @(posedge clk) disable iff(!resetn) 
    (!$isunknow(htrans)) && (!$isunknow(haddr)) && (!$isunknow(hmastlock)) && (!$isunknow(hreadyout)) && (!$isunknow(hresp));
endproperty : singal_alway_valid
SIGNAL_AWAY_VALID : assert property (singal_alway_valid);

property signal_valid_when_htrans_not_IDLE;
@(posedge clk) disable iff(!resetn)
(htrans !=IDLE) |-> (!$isunknow(hburst)) && (!$isunknow(hprot)) && (!$isunknow(hsize)) && (!$isunknow(hnonsec)) && (!$isunknow(hexcl)) && (!$isunknow(hmaster))
                        (!$isunknow(hwrite));
endproperty : signal_valid_when_htrans_not_IDLE
SIGNAL_VALID_HTRANS_NOT_IDLE : assert property (signal_valid_when_htrans_not_IDLE);

property valid_in_write_data_phase;
    @(posedge clk) disable iff(!resetn)
    ((hready == 1) && (hrep == 0) && (hwrite == 1)) |->  (!$isunknow(hexokey));
endproperty : valid_in_write_data_phase
SINGAL_VALID_WRITE_DATA_PHASE : assert property (valid_in_write_data_phase);

property valid_in_read_data_phase;
    @(posedge clk) disable iff(!resetn)
    ((hready == 1) && (hresp == 0) && (hwrite == 0)) |->  (!$isunknow(hrdata)) && (!$isunknow(hexokey));
endproperty : valid_in_read_data_phase
SINGAL_VALID_WRITE_DATA_PHASE : assert property (valid_in_read_data_phase);

property p_htrans_stable_during_wait;
    @(posedge HCLK) disable iff (!HRESETn)
    (!$past(heady == 1)) |-> 
        (
            ($past(htrans) == IDLE && (htrans == IDLE || htrans == NONSEQ)) ||
            ($past(htrans) == BUSY && $past(hburst) == INCR) ||
            ($past(htrans) == BUSY && $past(hburst) != INCR && (htrans == BUSY || htrans == SEQ)) ||
            ($past(htrans) == NONSEQ && htrans == NONSEQ) ||
            ($past(htrans) == SEQ && htrans == SEQ)
        );
endproperty
a_htrans_stable_during_wait: assert property(p_htrans_stable_during_wait);

property p_hwdata_stable_during_wait;
    @(posedge clk) disable iff (!resetn)
    (hwrite && !$past(hready)) |-> (hwdata == $past(hwdata));
endproperty
a_hwdata_stable: assert property(p_hwdata_stable_during_wait);

property p_error_response_sequence;
    @(posedge clk) disable iff (!resetn)
    (hresp == 1'b1 && hreadyout == 1'b0) |=> (hresp == 1'b1 && hreadyout == 1'b1);
endproperty
a_error_response_seq: assert property(p_error_response_sequence);


property p_error_response_start_valid;
    @(posedge clk) disable iff (!resetn)
    (hresp == 1'b1 && hreadyout == 1'b1) |-> ($past(hresp) == 1'b1 && $past(hreadyout) == 1'b0);
endproperty
a_error_response_start: assert property(p_error_response_start_valid);

 property p_last_burst_single_not_be_busy;
     @(posedge clk) disable iff(!resetn)
    (hburst == SINGLE && hready) |=> (htrans != BUSY);
endproperty
a_last_burst_single_not_be_busy : assert property(p_last_burst_single_not_be_busy);

endinterface : ahb_if
`endif